config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  # 7 deadly routes
  #index
  get     "/users"           =>    "users#index", as: "users"
  #sign up:
  get     "/signup"            =>  "users#new", as: "new_user"
  post    "/users"           =>    "users#create"
  get     "/users/:id"       =>    "users#show", as: "user"
  get     "/users/:id/edit"  =>    "users#edit", as: "edit_user"
  put     "/users/:id"       =>    "users#update"
  patch   "/users/:id"       =>    "users#update"
  delete  "/users/:id"       =>    "users#destroy"

  # login
  get     "/login"              =>  "users#login_form"
  post    "/login"              =>  "users#create_login"

  # logout
  get     "/logout"             =>  "users#logout"

resources :posts
resources :comments
#####################################################################

#   # 7 deadly routes
#   get     "/posts"           =>    "posts#index", as: "posts"
#   get     "/posts/new"       =>    "posts#new", as: "new_post"
#   post    "/posts"           =>    "posts#create"
#   get     "/posts/:id"       =>    "posts#show", as: "post"
#   get     "/posts/:id/edit"  =>    "posts#edit", as: "edit_post"
#   put     "/posts/:id"       =>    "posts#update"
#   patch   "/posts/:id"       =>    "posts#update"
#   delete  "/posts/:id"       =>    "posts#destroy"
# ######################################################################
#
#   # 7 deadly routes
#   get     "/comments"           =>    "comments#index", as: "comments"
#   get     "/comments/new"       =>    "comments#new", as: "new_comment"
#   post    "/comments"           =>    "comments#create"
#   get     "/comments/:id"       =>    "comments#show", as: "comment"
#   get     "/comments/:id/edit"  =>    "comments#edit", as: "edit_comment"
#   put     "/comments/:id"       =>    "comments#update"
#   patch   "/comments/:id"       =>    "comments#update"
#   delete  "/comments/:id"       =>    "comments#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
    @comments = Comment.all
  end


  def new
  end


  def create
    @new_comment = Comment.create(
      content: params[:comment][:content],
      post_id: params[:comment][:post_id],
      user_id: params[:comment][:user_id]
    )

    if @new_comment
      redirect_to '/posts/' + @new_comment.post.id.to_s
    else
      redirect_to url_for(:controller => :comments, :action => :new)
    end
  end


  def show
    @comment = Comment.find(params[:id])
    @comment_user = @comment.user.username

		@user = User.find(params[:id])
		@user_posts = @user.posts

    if session[:post_id] # if logged in
      @message = "You're now logged in!"
    else
      @message = "You're not logged in yet"
    end
  end


  def edit
    @comment = Comment.find(params[:id])
  end


  def update
    @comment = Comment.find(params[:id])
    @comment.update({
      content: params[:comment][:content],
      post_id: params[:comment][:post_id],
      user_id: params[:comment][:user_id]
    })

    if (@comment)
      redirect_to url_for(:controller => :comments, :action => :index)
    else
      redirect_to url_for(:controller => :comments, :action => :edit)
    end
  end


  def destroy

    @comment = Comment.find(params[:id])
    puts @comment
    @comment.destroy

    redirect_to url_for(:controller => :comments, :action => :index)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
  end

  def create
    @new_post = Post.create(
      title: params[:post][:title],
      content: params[:post][:content],
      user_id: params[:post][:user_id]
    )

    if @new_post
      redirect_to url_for(:controller => :posts, :action => :index)
    else
      redirect_to url_for(:controller => :posts, :action => :new)
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_user = @post.user.username
    @comments = @post.comments

    if session[:post_id] # if logged in
      @message = "You're now logged in!"
    else
      @message = "You're not logged in yet"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update({
      title: params[:post][:title],
      content: params[:post][:content],
      user_id: params[:post][:user_id]
    })

    if (@post)
      redirect_to url_for(:controller => :posts, :action => :index)
    else
      redirect_to url_for(:controller => :posts, :action => :edit)
    end
  end

  def destroy
    Post.delete(params[:id])
    redirect_to url_for(:controller => :posts, :action => :index)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  ### 7 # deadly # methods # go # here: ###
  def index
    @message = "List of Users"
    @users = User.all
  end

  def new
    @message = "Sign up for my Blog app!"
  end

  def create
    @new_user = User.create(
      username: params[:user][:username],
      password: params[:user][:password],
      email: params[:user][:email]
    )

    if @new_user
      session[:user_id] = @new_user.id
      redirect_to url_for(:controller => :users, :action => :index)
    else
      redirect_to url_for(:controller => :users, :action => :new)
    end
  end

  def show
    @user = User.find(params[:id])

    @user_posts = @user.posts

    if session[:user_id] # if logged in
      @message = "You're now logged in!"
    else
      @message = "You're not logged in yet"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update({
      password: params[:user][:password],
      username: params[:user][:username],
      email: params[:user][:email]
    })

    if (@user)
      redirect_to url_for(:controller => :users, :action => :index)
    else
      redirect_to url_for(:controller => :users, :action => :edit)
    end
  end

  def destroy
    User.delete(params[:id])
    session.destroy
    redirect_to url_for(:controller => :users, :action => :index)
  end

  def login_form
    if session[:user_id] # if logged in
      @message = "You're already logged in!"
    else
      @message = "You're not logged in yet. Login below!"
    end
  end

  def create_login
    @user = User.where(username: params[:username], password: params[:password]).first

    if @user
      session[:user_id] = @user.id
      # redirect_to url_for(:controller => :users, :action => :index)
      redirect_to user_path(session[:user_id])
    else
      redirect_to url_for(:controller => :users, :action => :new)
    end
  end

  def logout
    session.destroy
    redirect_to url_for(:controller => :users, :action => :index)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>All Comment: </h1>

<h4><%= link_to ("Create new comment"), new_comment_path %></h4>

<br>

<h4><% @comments.each do |comment| %>
  <%= comment.id %>.
  <%= comment.post_id %>.
  <%= comment.content %> <br>

  || <%= link_to ("Comment show page"), comment_path(comment.id) %> ||
  <%= link_to 'Delete comment',  { action: :destroy, id: comment.id }, method: :delete %> ||
  <hr>

<% end %>
</h4>

app/views/comments/show.html.erb
<h2>Commented by <%= @user.username.capitalize %>:</h2>
<h4><%= @user.id %>.
Username: <%= @user.username.capitalize %><br>
Email: <%= @user.email %></h4>
<!-- Password: <%= @user.password %></h4> -->

<br>
<h4><%= @user.username.capitalize %>'s Posts:<br>
<% @user_posts.each do |post| %>
  <%= post.id %>.
  <%= link_to (post.title), post_path(post.id) %>
<% end %>
</h4>
<hr>






<!-- <h3>Add comment</h3>

<%= form_for Comment.new do |f| %>

  <%= f.label :content %>:
  <%= f.text_field :content %> <br><br>

  <%= f.label :user %><br>
  <%= f.collection_select :user_id, User.all, :id, :username %><br><br>

  <%= f.label :post %><br>
  <%= f.collection_select :post_id, Post.all, :id, :title %>

  <br><br>

  <%= f.submit %>
<% end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Chewy|Fredoka+One|Permanent+Marker|Righteous" rel="stylesheet">
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand logo" href="/posts">rails blog</a>
        </div>


        <div class="butts pull-left">
          <a href="/posts">Post</a>
          <a href="/comments">Comments</a>
          <a href="/users">User</a>
        </div>
        <div class="butts pull-right">
          <a href="/signup">Sign Up</a>
          <a href="/login">Log In</a>
          <a href="/logout">Log Out</a>
        </div>


          <!-- <% if @user %>
          <a href="/logout"><button type="button" class="btn btn-default navbar-btn pull-right">Sign out</button></a>
          <% end %>
          <p class="navbar-text pull-right"><%= "Welcome Back, #{@user.username.capitalize} !" if @user %> </p> -->
      </div>
    </nav>

    <div class="container">

      <%= yield %>

    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= form_for @post do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %> <br><br>

  <%= f.label :content %>:
  <%= f.text_field :content %> <br><br>

  <%= f.label :user %>: <br>
  <%= f.collection_select :user_id, User.all, :id, :username %>

  <br><br>

  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<h1>All Posts: </h1>

<h4><%= link_to ("Create new post"), new_post_path %></h4>
<hr>

<h4><% @posts.reverse.each do |post| %>
  <%= post.id %>.
  <%= post.title %> <br>
  <%= post.content %> <br>

  <br>

  || <%= link_to ("Post show page"), post_path(post.id) %> ||
  <%= link_to 'Delete post',  { action: :destroy, id: post.id }, method: :delete %> ||
  <hr>

<% end %>
</h4>

app/views/posts/new.html.erb
<h3>Create new post!</h3>

<%= form_for Post.new do |f| %>
  <%= f.label :title %>:<br>
  <%= f.text_field :title %><br><br>

  <%= f.label :content %>:<br>
  <%= f.text_field :content %><br><br>

  <%= f.label :user %>:<br>
  <%= f.collection_select :user_id, User.all, :id, :username %>

  <br><br>

  <%= f.submit "Submit New Post"%>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.user.username.capitalize %>'s Posts</h1>

<!-- <h3>Title: </h3><%= @post.id %>. <%= @post.title %> <br> -->
<!-- <h3>Review: </h3><%= @post.content %><br> -->
<!-- <h3>Post show page</h3> -->

<h3>[ Title ]</h3>
<h4><%= @post.id %>.
<%= @post.title %></h4>

<h3>[ Review ]</h3>
<h4><%= @post.content %></h4>

<br>

<h4>[ Written by ]:</h4>
<h4><%= @post.user.username %></h4>

<hr>

<h3>[ Your Comments ]</h3><br>

<h4><% @comments.each do |comment| %>
  || <%= comment.content %> ||
  <%= link_to ("Show Comment"), comment_path(comment.id) %> ||
<% end %>
</h4>

<br>

<%= form_for Comment.new do |f| %>

  <%= f.label :content %> :
  <%= f.text_field :content %> <br><br>

  <%= f.label :user %> :
  <%= f.collection_select :user_id, User.all, :id, :username %>
<br><br>
  <%= f.label :post %> :
  <%= f.collection_select :post_id, Post.all, :id, :title %>

  <br><br>

  <%= f.submit "Submit Comment"%>
<% end %>

<br><br>



<!-- <h3 class="heading">Title: <%= @post.title if @post.title %></h3><br/>
<div class="row">
	<div class="text-center post">
		<a href="/users/<%= @post.user.id %>">Username: <%= @post.user.username %></a>
	</div>

	<div class="text-center post-content">
		<%= @post.content %>
	</div>
</div> -->


<!-- <div class="row">
	<% @post.comments.each do |comment| %>
	<div class="text-center user">
		<a href="/user/<%= comment.user.id %>"> <%= comment.user.username %></a>
	</div>
	<div class="text-center user-content">
	  <%= comment.content %>
	</div>

	<% end %>
<h4 class='text-center'>Written by: <%= @post.user.username %></h4>
  <div class="col-sm-12 text-center">

	  <form method="POST" action="/posts">
	    <input type="hidden" name="post_id" value="<%= @post.id %>"><br>
	  	<textarea maxlength="255" cols="60" rows="5" name="message" placeholder="Add Your Comment"></textarea><br>
	  	<input class="btn btn-default" type="submit">
	  </form>

  </div>

</div> -->

app/views/users/edit.html.erb
<h1>Edit your account:</h1>

<%= form_for @user do |f| %>

  <%= f.label :username %>:
  <%= f.text_field :username %> <br><br>

  <%= f.label :email %>:
  <%= f.text_field :email %> <br><br>

  <%= f.label :password %>:
  <%= f.text_field :password %> <br><br>

  <%= f.submit %>

<% end %>

app/views/users/index.html.erb
<h1><%= @message %></h1>

<h4><% @users.each do |user| %>
  <%= user.id %>.
  <%= user.username.capitalize %>,<br>
  Password: <%= user.password %>,<br>
  Email: <%= user.email %>

  <br><br>

  <%= link_to ("User show page"), user_path(user.id) %> |
  <%= link_to 'Delete user',  { action: :destroy, id: user.id }, method: :delete %>
  <hr><br>

<% end %></h4>

app/views/users/login_form.html.erb
<h1>Sign in!</h1>

<div><%= @message %></div>

<br><br>

<%= form_tag("/login", method: "post") do %>

  <%= label_tag(:username, "Username:") %>
  <%= text_field_tag(:username) %><br><br>

  <%= label_tag(:password, "Password:") %>
  <%= text_field_tag(:password) %><br><br>

  <%= submit_tag("Log In") %>
<% end %>

app/views/users/logout.html.erb
<h1>Come back and blog more soon!</h1>

app/views/users/new.html.erb
<h1>Register for my Blog app!</h1>

<%= form_for User.new do |f| %>

  <%= f.label :username %>:<br>
  <%= f.text_field :username %> <br><br>

  <%= f.label :email %>:<br>
  <%= f.text_field :email %> <br><br>

  <%= f.label :password %>:<br>
  <%= f.text_field :password %> <br><br>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div><h1><%= @message %></h1></div>

<br><br>

<h4><%= @user.id %>.
Username: <%= @user.username.capitalize %>,<br>
Email: <%= @user.email %>,<br>
Password: <%= @user.password %></h4>

<hr>

<h4><div>Posts by this <%= @user.username.capitalize %>:</div><br>

<% @user_posts.each do |post| %>
  <%= post.id %>.
  <%= link_to (post.title), post_path(post.id) %>
  <br><br>
<% end %>
</h4>